apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: deployment
        tier: backend
        track: stable
    spec:
      containers:
        - name: backend
          image: danielbahrami/fortune-cookie-backend:master
          env:
            - name: REDIS_DNS
              value: service_database
          ports:
            - containerPort: 90
---
apiVersion: v1
kind: Service
metadata:
  name: deployment
spec:
  selector:
    app: deployment
    tier: backend
  ports:
    - protocol: TCP
      port: 90
      targetPort: http
