apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-backend
  labels:
    app: deployment-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-backend
  template:
    metadata:
      labels:
        app: deployment-backend
    spec:
      containers:
        - name: deployment-backend
          image: danielbahrami/fortune-cookie-backend
          env:
            - name: REDIS_DNS
              value: service_database
---
apiVersion: v1
kind: Service
metadata:
  name: service-backend
  labels:
    app: deployment-backend
spec:
  type: NodePort
  selector:
    app: deployment-backend
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010