apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        track: stable
    spec:
      containers:
        - name: deployment-backend
          image: danielbahrami/fortune-cookie-backend:master
          env:
            - name: REDIS_DNS
              value: service_database
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
    tier: backend
  ports:
    - protocol: TCP
      port: 8010
      targetPort: http
