apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: deployment
        tier: frontend
        track: stable
    spec:
      imagePullSecrets:
        - name: secret/frontend
      containers:
        - name: frontend
          image: danielbahrami/fortune-cookie-frontend:master

---
apiVersion: v1
kind: Service
metadata:
  name: deployment
spec:
  selector:
    app: deployment
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
