apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-frontend
  labels:
    app: deployment-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-frontend
  template:
    metadata:
      labels:
        app: deployment-frontend
    spec:
      containers:
        - name: frontend
          image: danielbahrami/fortune-cookie-frontend
        imagePullSecrets:
          - name: Secret/frontend
---
apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  labels:
    app: deployment-frontend
spec:
  type: NodePort
  selector:
    app: deployment-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

