apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  labels:
    app: deployment-frontend
spec:
  type: NodePort
  selector:
    app: deployment-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
