apiVersion: v1
kind: Service
metadata:
  name: service-backend
  labels:
    app: deployment-backend
spec:
  type: NodePort
  selector:
    app: deployment-backend
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010
