apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-backend
  labels:
    app: deployment-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-backend
  template:
    metadata:
      labels:
        app: deployment-backend
    spec:
      containers:
      - name: deployment-backend
        image: SE05-CD/backend:master
        env:
          - name: REDIS_DNS
            value: service_database
