version: '3.7'

services:
  #Start of frontend services
  frontend:
    build: ../frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_DNS=backend
  #End of frontend services
  #Start of backend service
  backend:
    build: ../backend
    depends_on:
      - redis
    
    environment:
      - REDIS_DNS=redis

    ports:
      - "8010:8010"
  #End of backend service
  #Start of redis service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  #End of redis service