name: Pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  check-out:
    name: Check out repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload repo
        uses: actions/upload-artifact@v2
        with:
          name: Repository
          path: .
      - name: Upload backend
        uses: actions/upload-artifact@v2
        with:
          name: Backend
          path: ./backend
      - name: Upload frontend
        uses: actions/upload-artifact@v2
        with:
          name: Frontend
          path: ./frontend

  build-backend:
    name: Build backend
    needs: check-out
    runs-on: ubuntu-latest
    steps:
      - name: Download backend
        uses: actions/download-artifact@v2
        with:
          name: Backend
          path: .
      - name: Build backend
        run: go mod tidy && go mod download && go build
      - name: Upload backend
        uses: actions/upload-artifact@v2
        with:
          name: Backend
          path: .

  build-frontend:
    name: Build frontend
    needs: check-out
    runs-on: ubuntu-latest
    steps:
      - name: Download frontend
        uses: actions/download-artifact@v2
        with:
          name: Frontend
          path: .
      - name: Build frontend
        run: go mod tidy && go mod download && go build
      - name: Upload frontend
        uses: actions/upload-artifact@v2
        with:
          name: Frontend
          path: .

  test-frontend:
    name: Test frontend
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Download frontend
        uses: actions/download-artifact@v2
        with:
          name: Frontend
          path: .
      - name: Test frontend
        run: go test
      - name: Upload test
        uses: actions/upload-artifact@v2
        with:
          name: Frontend
          path: .

  backend-docker-image:
    name: Build and push backend image
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: danielbahrami/fortune-cookie-backend
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  frontend-docker-image:
    name: Build and push frontend image
    needs: [build-frontend, test-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: danielbahrami/fortune-cookie-frontend
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
