name: ci
on:
  push:
    branches:
      - master

jobs:
  clone-down:
    name: clone down repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: upload repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
      - name: upload backend
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: ./backend
      - name: upload frontend
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: ./frontend

  build-backend:
    name: build backend
    needs: clone-down
    runs-on: ubuntu-latest
    steps:
      - name: download backend
        uses: actions/download-artifact@v2
        with:
          name: backend
          path: .
      - name: build backend
        run: go mod tidy && go mod download && go build
      - name: upload backend
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: .

  build-frontend:
    name: build frontend
    needs: clone-down
    runs-on: ubuntu-latest
    steps:
      - name: download frontend
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: .
      - name: build frontend
        run: go mod tidy && go mod download && go build
      - name: upload frontend
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: .

  test-frontend:
    name: test frontend
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: download frontend
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: .
      - name: test frontend
        run: go test
      - name: upload test
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: .
