name: Build and test
on:
  push:
    branches: [dev]
  pull_request:
    branches: [master]

jobs:
  check-out:
    name: Check out repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload repo
        uses: actions/upload-artifact@v2
        with:
          name: Repository
          path: .
      - name: Upload backend
        uses: actions/upload-artifact@v2
        with:
          name: Backend
          path: ./backend
      - name: Upload frontend
        uses: actions/upload-artifact@v2
        with:
          name: Frontend
          path: ./frontend

  build-backend:
    name: Build backend
    needs: check-out
    runs-on: ubuntu-latest
    steps:
      - name: Download backend
        uses: actions/download-artifact@v2
        with:
          name: Backend
          path: .
      - name: Build backend
        run: go mod download && go build
      - name: Upload backend
        uses: actions/upload-artifact@v2
        with:
          name: Backend
          path: .

  build-frontend:
    name: Build frontend
    needs: check-out
    runs-on: ubuntu-latest
    steps:
      - name: Download frontend
        uses: actions/download-artifact@v2
        with:
          name: Frontend
          path: .
      - name: Build frontend
        run: go mod download && go build
      - name: Upload frontend
        uses: actions/upload-artifact@v2
        with:
          name: Frontend
          path: .

  test-frontend:
    name: Test frontend
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Download frontend
        uses: actions/download-artifact@v2
        with:
          name: Frontend
          path: .
      - name: Test frontend
        run: go test
      - name: Upload test
        uses: actions/upload-artifact@v2
        with:
          name: Frontend
          path: .

  linter:
    name: Go linter
    strategy:
      fail-fast: false
      matrix:
        go: ["1.19"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: ${{ matrix.go }}
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
          install-go: false
          cache-key: ${{ matrix.go }}
