name: Deploy to Kubernetes
on:
  push:
    branches: [master]

jobs:
  check-out:
    name: Check out repo
    needs:
      - backend-docker-image
      - frontend-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload frontend
        uses: actions/upload-artifact@v2
        with:
          name: manifests
          path: ./deployment

  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    needs: check-out
    steps:
      - name: Download manifests
        uses: actions/download-artifact@v2
        with:
          name: manifests
          path: .
      - name: Inject release versions
        run: |
          sed -i "s/BACKEND_VERSION/${{ github.ref_name }}/g" backend.yaml
          sed -i "s/FRONTEND_VERSION/${{ github.ref_name }}/g" frontend.yaml
          echo ${{ github.ref_name }}
      - name: Apply manifests
        run: |
          kubectl apply -f .
